import type { Metadata } from "next";
import localFont from "next/font/local";
import TopNav from "./components/nav";
import "./globals.css";
// import "prismjs/components/prism-javascript";
// import "prismjs/themes/prism.css";
// import prismjs from "prismjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout rendered");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNav />
        <main className="app-layout">{children}</main>
      </body>
    </html>
  );
}
